import { useState } from "react";
import { useI18n } from "../lib/i18n";
import { generationExample, generationPrompt } from "../lib/generation";
import { HelpMedia } from "./HelpMedia";
import { CrossNotationCase } from "./CrossNotationCase";

function download(name:string,text:string,type="text/plain") {
  const url=URL.createObjectURL(new Blob([text],{type:`${type};charset=utf-8`}));
  const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function HelpView({page,onImport}:{page:"generate"|"faq";onImport:()=>void}) {
  const {t,locale}=useI18n();const [copied,setCopied]=useState(false),[fallback,setFallback]=useState(false);
  const prompt=generationPrompt(locale);
  const copy=async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);setFallback(false);}catch{download(`plyloom-ai-prompt-${locale}.txt`,prompt);setFallback(true);}};
  const faq=[
    [t("Как показать связи только выделенного листа?","How do I show connections for one selected sheet?"),t("В обзоре всех листов включите «Только для выделенного листа» и нажмите заголовок нужного листа. Останутся его межлистовые связи и золотые линии ко всем появлениям общих узлов на других листах. Переключатели «Между листами» и «Один ID» работают отдельно. Все листы и их внутренние связи остаются видны. Снятие отметки возвращает общий обзор связей.","In the sheet overview, enable Selected sheet only and click the required sheet header. Its cross-sheet relations and gold lines to every other appearance of shared nodes remain. Between sheets and Same ID still work independently. All sheets and their local relations remain visible. Uncheck to restore all overview connections.")],
    [t("Как сразу выбрать или выключить все типы?","How do I select or turn off all types?"),t("Нажмите «Фильтр». У типов узлов и типов связей свои кнопки «Выбрать все» и «Выключить все». Они меняют только свою группу. После «Выключить все» можно отметить один нужный тип. Переключатель «Скрывать / Приглушать» решает, убрать отфильтрованное с экрана или показать бледным на месте; данные и позиции сохраняются. «Показать всё» сбрасывает фильтр.","Press Filter. Node types and Relation types each have Select all and Turn off all buttons, acting on that group only. You can turn everything off, then select one type. The Hide / Dim switch either removes filtered objects from the screen or shows them faded in place; data and positions are preserved. Show all resets the filter.")],
    [t("Как попросить ИИ создать проект с атрибутами?","How do I ask AI for a project with attributes?"),t("В «Справка → Подготовить проект с ИИ» скопируйте стандарт PlyLoom v3 вместе с примером и добавьте свои материалы. В types.attributes задаются определения: id, название, dataType и варианты options для select. В attributes каждого узла находятся значения по ID определения. Пример показывает все семь типов данных, типы и теги листов и общий узел. null означает неизвестное значение добавленного атрибута. Сохраните ответ как .plyloom или .json, откройте через «Проект» и проверьте значения. PlyLoom сам к внешнему ИИ не подключается.","In Help → Prepare a project with AI, copy the PlyLoom v3 contract and example, then add your materials. types.attributes defines id, label, dataType and options for select. Each node’s attributes maps definition IDs to values. The example covers all seven data types, sheet classification and a shared node. null means an attached attribute with an unknown value. Save the response as .plyloom or .json, open it through Project and review the values. PlyLoom does not connect to an external AI service.")],
    [t("Чем обзор листов отличается от разворота?","How does Helicopter view differ from Spread?"),t("Режим «Листы» открывает редактор одного листа. Кнопка «− Все листы» справа сверху выводит на обзор всех листов, а «+» в углу листа возвращает к его редактированию. Перетаскивайте лист за заголовок, узел — внутри листа, фон — для перемещения обзора. Масштаб: кнопки внизу, Ctrl/⌘ + колесо или два пальца. Координаты листа и его узлов независимы и сохраняются в .plyloom. Перетаскивание узла не переносит его на другой лист. Разворот нужен для сравнения 2–6 выбранных листов рядом в заданных пропорциях.","Sheets opens a single-sheet editor. The upper-right minus opens an overview of all sheets; each sheet’s plus returns to editing. Drag headers to move whole sheets, nodes to move them within their sheet, and the background to pan. Zoom with the footer buttons, Ctrl/⌘ + wheel or two fingers. Sheet and node positions are independent and saved in .plyloom. Dragging a node does not transfer it to another sheet. Spread compares 2–6 selected sheets side by side in chosen proportions.")],
    [t("Что делает «Все на один лист»?","What does All-to-1 do?"),t("Показывает каждую сущность один раз в общем представлении. Узлы можно перетаскивать и оптимизировать: это отдельное расположение, которое сохраняется в проекте. Через плюс доступны общий текст и атрибуты. Исходные листы, членства и их координаты сохраняются. Сплошные и пунктирные связи отражают принадлежность к исходным листам.","It shows each entity once in a shared view. Drag or optimize nodes in a separate arrangement saved in the project. The plus opens shared text and attributes. Source sheets, memberships and their positions are retained. Solid and dashed connections still reflect the original sheet memberships.")],
    [t("Где новый проект, типы и атрибуты?","Where are projects, types and attributes?"),t("В меню «Типы» четыре вкладки. В «Листах» сверху теги, ниже типы листов и сами листы. У листа один тип и несколько тегов. В «Атрибутах» задайте название и тип данных, затем добавьте значение к узлу в свойствах или через плюс на листе. Словари входят в .plyloom. Новый проект создаётся через «Проект → Новый пустой проект».","Types has four tabs. Sheets lists tags, sheet types, then project sheets. Each sheet has one type and multiple tags. Define a name and data type under Attributes, then attach a value in node properties or with the plus on the sheet. Dictionaries are saved in .plyloom. Start a project with Project → New empty project.")],
    [t("Какие диаграммы можно импортировать?","Which diagrams can I import?"),t("В меню «Проект» доступны draw.io, Obsidian Canvas и BPMN с данными расположения DI. Они добавляют листы после предпросмотра. Сохраняются координаты, размеры и базовые формы; для draw.io и BPMN — точки маршрутов. Сложные фигуры, изображения, фоны, вложения и специальные маркеры поддержаны не полностью: ограничения видны до импорта. .plyloom открывает целый проект и сохраняет все его данные.","Project imports draw.io, Obsidian Canvas and BPMN with DI layout data. They append sheets after preview. Coordinates, sizes and basic shapes are retained; draw.io and BPMN also retain route points. Complex shapes, images, backgrounds, attachments and special markers have limitations shown before import. .plyloom opens a whole project and preserves all its data.")],
    [t("Как читать оглавление на телефоне?","How do I read Contents on a phone?"),t("Схема показывает карточки листов и линии между ними. Выберите лист в поле Выделить связи листа, чтобы уменьшить шум. Число на линии — количество связей, после точки — количество общих узлов. Нажмите карточку для открытия листа или линию для разворота. Переключатель Схема / Список меняет представление вручную.","The diagram shows sheet cards and their connections. Focus on a sheet to reduce clutter. A line badge shows relation count, then shared-node count after the dot. Tap a card to open a sheet or a line to open a spread. Diagram / List switches the presentation manually.")],
    [t("Что делать с большим листом?","What do I do with a large sheet?"),t("Ничего, если он отвечает на один вопрос: размер сам по себе не ошибка, и лимита узлов в PlyLoom нет. Читать большой лист помогают «Фильтр» и строка поиска в нём: условия по типам и атрибутам, поиск по имени, тексту, тегам, листу и значениям атрибутов, кнопка «Только найденные» в полосе листов. Делить лист стоит, когда он отвечает на два разных вопроса. Тогда в панели листа выберите признак — атрибут, теги или тип узла — и нажмите «Разложить»: на каждое значение получится свой лист с этим значением в названии. Узел с несколькими значениями встанет сразу на несколько листов, узлы без значения соберутся на листе «Без значения». Координаты, оформление и связи сохранятся, «Отменить» вернёт прежнюю карту. Лист, разложенный по одиночному выбору, разложить по тому же признаку второй раз уже нельзя: там одно значение. По множественному выбору и по тегам повтор возможен — узел и правда несёт несколько значений.","Nothing, if it answers one question: size alone is not a mistake, and PlyLoom has no node limit. Large sheets are read with Filter and its search line: conditions on types and attributes, search across name, body, tags, sheet and attribute values, and the Matches only button in the sheet strip. Divide a sheet when it answers two different questions. In that case pick a key in the sheet panel \u2014 an attribute, node tags or the node type \u2014 and press Lay out: you get one sheet per value, named after it. A node with several values stands on several of those sheets, and nodes with nothing set gather on a No value sheet. Coordinates, appearance and relations are preserved, and Undo restores the previous map. A sheet made from a single-choice value cannot be laid out by the same key again — it holds one value. With multiple choice or tags a second pass is possible, because a node really does carry several values.")],
    [t("Что делает «Оптимизировать расположение»?","What does Optimize layout do?"),t("Кнопка под листом пробует расположить связанные ноды рядом, развести карточки и уменьшить пересечения и общие участки линий. Работает при редактировании листа, в Развороте и в режиме «Все на один лист». В Развороте учитываются все видимые слои, их связи и линии одного ID; на телефоне — открытый слой и боковые переходы. Результат вписывается в экран и сохраняется в JSON. «Отменить» возвращает всю расстановку одним действием; расчёт можно прервать. «Вписать» после оптимизации меняет масштаб, сохраняя позиции. Это приблизительный подбор, не гарантия отсутствия пересечений: для плотных видов оценка ограничена выборкой из 400 линий.","The button below the sheet tries nearby placements for connected nodes, separates cards, and reduces crossings and shared line segments. It works while editing a sheet, in Spread and in All-to-1. A spread includes all visible layers, their connections and same-ID lines; on a phone it includes the open layer and side references. The result is fitted to the screen and saved in native JSON. Undo restores the entire arrangement in one step, and a calculation can be cancelled. After optimization, Fit changes the zoom while keeping positions. This is a heuristic, not a guarantee of a crossing-free drawing: dense views are evaluated using a sample of up to 400 lines.")],
    [t("Как различать три вида линий?","How do I distinguish the three line types?"),t("Линия внутри слоя использует стиль своего типа. Пунктирная стрелка — к сущности другого листа. Бронзово-золотая линия без стрелки — одна и та же сущность на нескольких листах, с одним ID и общим телом. Наведите на «Легенда линий» или нажмите её на телефоне.","A relation within a sheet uses its type’s line style. A dashed arrow connects to an entity on another sheet. An amber-bronze line without an arrow joins the same entity across sheets, sharing one ID and body. Hover over Line legend, or tap it on a phone.")],
    [t("С чего начать?","Where do I start?"),t("Выберите лист в верхней полосе. Стрелки и Alt+← / Alt+→ перелистывают карту. «+ Узел» создаёт узел на выбранном листе. Двойной клик по пустому месту делает то же на листе.","Choose a sheet in the top strip. Use arrows or Alt+← / Alt+→ to turn pages. + Node creates a node on the selected sheet. Double-click empty sheet space to create one there.")],
    [t("Что делает плюс на узле?","What does the plus on a node do?"),t("Раскрывает название, текст и атрибуты прямо на листе. Сначала создайте определения атрибутов в словаре, затем выберите нужные для узла. Доступны текст, число, дата, да/нет, ссылка и список вариантов. Правки общие для всех появлений одного ID. Минус сворачивает редактор.","It opens the name, text and attributes on the sheet. Define attributes in the dictionary, then choose which to attach to a node. Supported data types are text, number, date, yes/no, URL and choice. Edits are shared across all appearances of the same ID. Minus collapses the editor.")],
    [t("Лист и слой — это одно и то же?","Are sheets and layers the same thing?"),t("Да. Лист — отдельная карта, слой — её представление в развороте или стопке. Цвет и название помогают узнавать её в любом режиме.","Yes. A sheet is one map; a layer is that sheet shown in a spread or stack. Its name and color remain consistent across views.")],
    [t("Что за полупрозрачные сущности за пунктиром?","What are the faded entities beyond the dashed line?"),t("Это ссылки на ноды других листов. Нажатие открывает лист с этой сущностью. Когда она уже видна на другом слое разворота, ссылка убирается, а линия идёт к самой ноде. За границей остаются только связи с листами вне текущего вида.","These are references to nodes on other sheets. Click one to open that entity’s sheet. If the entity is already visible in another spread layer, the reference is removed and the edge connects to the actual node. Only references outside the current view remain at the boundary.")],
    [t("Как собрать разворот?","How do I compose a spread?"),t("Выберите 2–6 слоёв и пропорции. В каждом заголовке «Слой:» можно выбрать другой лист. Три слоя — высокий слева; пять — широкий ряд посередине. Автоматическая раскладка подстраивается под место. После ручного перемещения или оптимизации позиции сохраняются, а «вписать» подбирает масштаб. Для новых пропорций можно снова оптимизировать расположение. «Боковые переходы» скрывает внешние карточки; тонкая рамка показывает активный слой.","Choose 2–6 layers and their proportions. Select a sheet in each Layer: header. Three layers have a tall left sheet; five have a wide middle row. Automatic layout adapts to the space. After a drag or optimization, positions are saved and Fit adjusts the zoom. Optimize again after changing proportions if needed. Side references hides external cards; a thin frame marks the active layer.")],
    [t("Почему на телефоне один лист?","Why is only one sheet shown on a phone?"),t("На узком экране разворот показывает активный лист, а полоса сверху позволяет быстро переключаться. Затухающие ссылки учитывают реально видимый лист. Стопку можно двигать одним пальцем и масштабировать двумя; её настройки сворачиваются.","On narrow screens, the spread shows its active sheet, with quick switching in the top strip. Faded references are computed for the sheet actually visible. Pan the stack with one finger and zoom with two; its settings can be collapsed.")],
    [t("Как читать стопку?","How do I read the stack?"),t("Переключайтесь между «Построчно» и «Узлы и связи». Видны все узлы выбранных листов. Группировка по типу листа или выбранному тегу меняет порядок слоёв. «Оптимизировать расположение» переставляет узлы только в стопке; исходные листы сохраняют позиции. Для чтения крупного проекта увеличьте масштаб и выберите активный слой.","Switch between Rows and Nodes & edges. All nodes on selected sheets are included. Grouping by sheet type or a chosen tag orders the layers. Optimize layout rearranges the stack only; the source sheets retain their positions. Zoom in and focus a layer to read larger projects.")],
    [t("Как поместить одну сущность на несколько листов?","How can one entity appear on multiple sheets?"),t("Выберите узел и в свойствах нажмите «+ ещё лист…». Это тот же ID с общими текстом и атрибутами, с отдельными координатами на каждом листе. Новая связь между двумя узлами создаётся кнопкой «+ Связь» в верхней панели или действием «+ связать с…» в свойствах узла.","Select a node and choose + another sheet… in its properties. It keeps the same ID, text and attributes, with a separate position on each sheet. To connect two nodes, use + Relation in the top bar or + link to… in node properties.")],
    [t("Как работают типы листов и фильтры?","How do sheet types and filters work?"),t("Тип и теги классифицируют лист. Они не ограничивают типы его узлов и связей. В панели «Фильтр» можно отобрать узлы по типам и атрибутам: разные условия действуют вместе, отметки внутри одного — любая из них (у атрибута «множественный выбор» это переключается на «все выбранные»). Строка поиска вверху панели ищет по имени, телу, тегам узла, названию листа и значениям атрибутов — области можно выключать. Несколько слов означают И: найтись должно каждое. Enter переходит к следующему совпадению, а кнопка «Только найденные» в полосе листов оставляет в списке листы с совпадениями. У атрибута есть отдельные состояния «не заполнено» и «нет атрибута». Узел, который вы создаёте, открываете или меняете, остаётся на экране, пока фильтр не изменится. Сплошные линии соединяют узлы на одном листе, пунктирные — между листами, золотые — появления одного ID.","Type and tags classify a sheet without restricting its node or relation types. The Filter panel selects nodes by type and attribute: different conditions apply together, checks inside one condition mean any of them (a multiple-choice condition can require all of them instead). The search line at the top of the panel looks in the node name, body, node tags, sheet name and attribute values; each area can be turned off. Several words mean AND: every one of them has to be found. Enter goes to the next match, and Matches only in the sheet strip keeps just the sheets that hold one. Attributes have separate empty and no attribute states. A node you create, open or edit stays on screen until the filter changes. Solid lines connect nodes on one sheet, dashed lines connect sheets, and gold lines join appearances of one ID.")],
    [t("Что проверяет lint?","What does lint check?"),t("Пустые и необычно крупные листы, отсутствующие концы связей, несвязанные ноды и подозрительные членства. Подсказка о втором листе — эвристика: смысл границы решает читатель. Корректность источников линт не проверяет.","It notes unusually large or empty sheets, missing endpoints, isolated nodes and suspicious memberships. Suggestions to add a second sheet are heuristics; the reader decides whether the boundary makes sense. Lint does not verify source accuracy.")],
    [t("Как загрузить и сохранить карту?","How do I import and save a map?"),t("Меню «Проект» содержит открытие и скачивание .plyloom, отдельный импорт и экспорт draw.io. CSV и другие экспорты находятся в подразделе «Другие форматы и примеры». .plyloom сохраняет общие ID, членства, словари, атрибуты, геометрию и расположение листов. JSON Canvas создаёт отдельные карточки для появлений, экспорт в дерево для проектов v3 недоступен, потому что теряет новые данные. Для дальнейшего редактирования храните PlyLoom JSON. Формат для ИИ — в соседней вкладке.","Project contains .plyloom open/download and separate draw.io import/export. CSV and other exports are under Other formats and examples. .plyloom preserves shared IDs, memberships, dictionaries, attributes, geometry and sheet positions. JSON Canvas makes separate cards for appearances; tree export is unavailable for v3 projects because it loses the new data. Keep PlyLoom JSON for further editing. The AI format is in the adjacent tab.")],
    [t("Куда уходят данные и что переводится?","Where is data sent, and what is translated?"),t("Этот HTML работает без сервера и не отправляет карту в сеть. Автосохранение — в IndexedDB браузера, в простое; прежняя запись переносится автоматически, оно не заменяет скачанную резервную копию. RU/ENG переводит интерфейс и названия встроенных примеров. Ваши тексты и ID не переписываются; тела демонстрационных узлов остаются на исходном языке.","This HTML runs without a server and does not send the map over the network. Autosave uses IndexedDB during idle time and migrates older saves; it does not replace a downloaded backup. RU/ENG translates the interface and built-in example names. Your prose and IDs are not rewritten; demo node bodies remain in their original language.")],
    [t("Как сохранить фильтр и создать умный лист?","How do I save a filter or create a smart sheet?"),t("В панели фильтра откройте «Сохранённые виды»: здесь сохраняются условия, режим и выбранные листы. Умный лист сам обновляет состав по условиям узлов, сохраняя их обычные членства. Запрос можно заменить здесь же; в свойствах листа — превратить результат в обычный лист. Последние шесть запросов остаются в браузере и очищаются отдельно.","Open Saved views in the filter panel to save conditions, mode and chosen sheets. A smart sheet follows the node conditions while keeping ordinary memberships. Replace the query here, or turn the result into an ordinary sheet in sheet properties. The last six queries stay in this browser and can be cleared separately.")],
    [t("Почему большая карта показана без текста?","Why does a large map show no text?"),t("На мелком масштабе большие сцены рисуются упрощённо. Нажмите узел, увеличьте масштаб или используйте поиск и Enter — появится читаемая карточка. За краем экрана объекты временно не рисуются; данные сохраняются полностью.","Large scenes use simplified rendering at small scale. Click a node, zoom in or use search and Enter to show a readable card. Offscreen objects are temporarily omitted from rendering; their data is retained.")],
  ];
  return <article className="help-view" key={page}><div className="help-content">
    <p className="help-eyebrow">PlyLoom / {page==="generate"?"AI FORMAT":"FIELD GUIDE"}</p>
    <h2>{page==="generate"?t("Как сгенерировать готовый к загрузке документ?","How do I generate a file ready to import?"):t("FAQ / ЧАВО","FAQ")}</h2>
    {page==="generate"?<>
      <p className="help-lead">{t("Передайте ИИ стандарт v3 с примером словарей, типов листов, тегов и семи типов атрибутов. Добавьте свои материалы; ответ сохраните как .plyloom или .json и проверьте после открытия.","Give the AI the v3 contract with dictionaries, sheet types, tags and all seven attribute data types. Add your materials, save the response as .plyloom or .json and review it after opening.")}</p>
      <HelpMedia topic="ai"/>
      <ol className="help-steps"><li>{t("Скопируйте стандарт","Copy the standard")}<span>{t("Добавьте вопрос и источники в конец запроса.","Append your question and sources to the prompt.")}</span></li><li>{t("Сохраните ответ как .json","Save the response as .json")}<span>{t("Без обёртки Markdown. Проверьте факты и источники.","No Markdown wrapper. Review the facts and sources.")}</span></li><li>{t("Загрузите и прочитайте","Import and review")}<span>{t("PlyLoom проверит структуру. Затем проверьте границы листов.","PlyLoom checks the structure. Then review sheet boundaries.")}</span></li></ol>
      <div className="help-actions"><button className="primary-button" onClick={()=>void copy()}>{t("Скопировать стандарт для ИИ","Copy AI standard")}</button><button onClick={()=>download(`plyloom-example-${locale}.json`,JSON.stringify(generationExample(locale),null,2),"application/json")}>{t("Скачать пример JSON","Download example JSON")}</button><button onClick={onImport}>{t("Загрузить файл","Import a file")}</button></div>
      {(copied||fallback)&&<p role="status">{fallback?t("Буфер недоступен — стандарт скачан текстовым файлом.","Clipboard unavailable; the standard was downloaded as a text file."):t("Стандарт скопирован. Добавьте свои материалы перед отправкой ИИ.","Standard copied. Add your materials before sending it to an AI.")}</p>}
      <details open className="help-contract"><summary>{t("Стандарт PlyLoom v3, атрибуты и полный пример","PlyLoom v3 contract, attributes and complete example")}</summary><pre>{prompt}</pre></details>
    </>:<><p className="help-lead">{t("Одна сущность. Несколько контекстов. Карта, которую можно читать по частям.","One entity. Several contexts. A map you can read one part at a time.")}</p><HelpMedia topic="lines"/><details className="help-media-extra"><summary>{t("Показать: принцип общего редактирования","Show: shared editing")}</summary><HelpMedia topic="editing"/></details><details className="help-media-extra case-details"><summary>{t("Сквозной пример: BPMN, C4, UML, требования и риски","Cross-model example: BPMN, C4, UML, requirements and risks")}</summary><CrossNotationCase/></details><div className="faq-list">{faq.map(([question,answer],i)=><details key={i} open={i===0}><summary>{question}</summary><p>{answer}</p></details>)}</div></>}
  </div></article>;
}
